version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: umkm_postgres
    restart: always
    environment:
      POSTGRES_USER: umkm_user
      POSTGRES_PASSWORD: umkm_password
      POSTGRES_DB: umkm_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: umkm_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@umkm.local
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
